apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:RizaSatya/homelab.git
    targetRevision: main
    path: clusters/homelab/bootstrap
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: argoproj.io
      kind: ApplicationSet
      jsonPointers:
        - /spec/generators/0/git/cloneCredentials
        - /spec/template/spec/source/sourceCredentials
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
