apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webapps:aggregate-to-crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - "*"
