apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-riza
  namespace: web-riza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-riza
  template:
    metadata:
      labels:
        app: web-riza
    spec:
      containers:
      - name: web-riza
        image: rizasatyabudhi/web-riza:v1.1
        ports:
        - containerPort: 3000
