apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-riza
  namespace: web-riza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-riza
  template:
    metadata:
      labels:
        app: web-riza
    spec:
      containers:
      - name: web-riza
        image: rizasatyabudhi/web-riza:v1.2
        ports:
        - containerPort: 3000
        env:
        - name: OPENROUTER_API_KEY
          valueFrom:
              secretKeyRef:
                name: web-riza-secrets
                key: OPENROUTER_API_KEY
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: http://opentelemetry-collector.observability.svc.cluster.local:4318/v1/metrics
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: http/protobuf
        - name: OTEL_SERVICE_NAME
          value: web-riza
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: deployment.environment=homelab
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://opentelemetry-collector.observability.svc.cluster.local:4318/v1/metrics
