apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backstage-data
  namespace: backstage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
