organization:
  name: homelab

backend:
  baseUrl: http://backstage.backstage.svc.cluster.local:7007
  listen:
    port: 7007

catalog:
  locations:
    - type: url
      target: https://github.com/RizaSatya/homelab/blob/main/catalog-info.yaml
    
    - type: github-discovery
      target: https://github.com/RizaSatya/homelab
      rules:
        - pattern: apps/*/catalog-info.yaml
  
  rules:
    - allow: [Component, System, Group, Location]

permission:
  enabled: false

techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local
