apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgweb-bookmarks
  namespace: database-tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Mi
