---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: web-riza-secrets
  namespace: web-riza
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgCec0bAR7vf+RckQyHIQwdrcK9FaGASxGkuY6lGVWRDsm9vWe3w2r4+VKYGjbpZijgOvwuoA0vOFrys/9Pyc/rhz0i5O8CoIGpZbvtXJdY5NOnebUMKpkF+pNsGPO3TiambI/7OJeAaP0oMemrS7GihYI5JGbgMbkyRM6j1tG/wzQScHMSkSHTRka/GU+x+wAM1wdYkTc7nyubjrCrmq3Lt5wAZPTQv0MwMh2xVfhL37ELUKU2M6A0diuTL+vZzDlJd2Hu/B7bPl5IRGOhN3OsVHshJLlGUW0Uo5X+OcHu7c8p8DfVBp7zECKohxij84GpZ4yq+HwdJj39xbfder3idngiq6CkFiJY6hEymlVvd8XuXRbLbn+GNFIMa8dCP6FURqLcTJ7Q+1yldRw7Dn+QgOZ+0prCpH+hrwcfPnc8MdyCFdqgCsZuf0CbM5PU7/0JKX4YXi105cLl1xmcW8gO5gtfnnrRnKsR7/CO/QYB9xcfKGB6QmUhlfB9PQAxV5D8bJd7Vi4rGbEhfxPfJn9Te//oqRYqIUWON8UYvKt7YuEIDipkT36Nh4jdwjqLzQzEYtNP+tStLggNa5N3PtOrtkw7V3VpFGjwHHOawgvzUpyR0wUCxI/ZBqSh37p6Wh6S4s7h2C2uMwDqYYm6sJuiFHAMYlUvRsQtUTHE4NA2o+coZguhYqxpuukHfsawJTtYude8Up7AZzVIH5ZmD8l4Hix3/mgl8KMlXRkCnteXguvFCYe5byM1sYVHF7RkrWBhQV3DWDkBGuSe7NHXyyNkq6X1voab6nj+t
  template:
    metadata:
      name: web-riza-secrets
      namespace: web-riza
