---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgCRXOnvMrRxQi5s28X4pnpikVhP/P2rW7t0r3+6dnYUo2xr1nh0rmkTFOonIqcaRmN4Zg5S9CgdByLfrmnmBDsUYy1jb+60EFxtX31F2sBpZkRxks1xiPnbJMLVvv7jYgCddhHCbOtmO6jO+IBQ4VUWRN9muzRcc9dPwIO3Ra+G+3xKX65dzu9LOuZfVEwwUl8OZ4YyP03grYsrLJdOG5FuXYDNYYbe3KMl/fFmYi1HWTJ3FaNxbNAMLkbrvu6MFUlA8DZyWCrEYshkUx3j2Ll5b7eIO/+xWNPqhPyo/2joLtjNCgDVyS9sWIamvTU7ibKIKLvd11XpOeU/cwEId6FJvUr0r0jcZmC5G4hp+lQS2Yh4m0I6YmSMCWNugmRV8U5XX2daV4r1obUxQl/pW0pe4WgkpZI9aI/152mel1US/ZTfFzM4FTcK4h05p6+Tp5E+XDMW/SCbhgCHEH3yS5cVxAmwz4e03+0b1qL/52ITSEKUnDKcLlWZ0BNnAViJCHe9p0ILY4P4K+1gK3jw+GtRrNRWTLncedNzPqCYD2xuCnbeN218ItUudw/mfy0SHOU3fbf2dNMAR+ZmzYwkDJVY+5v2C2OBp+lah3qxci3Evi2EVDx1/mihUTUeDFogV8AHVyoNXlGNGuKPW2KKvp2dPHPsk3enTxQh4TAXEjJfdHqlIAJLXDgO/y3CMQzrClgr4bx79nsuAXz/b8Ls6QkVjQz7qhTiVJb5ZaxhLGFEPOnInZbmGPaxLjOE/DwLg+QWw+QaQjFfU7KK4Sy6PuQWs0HSidkGik9uvnFXwWEiqeZDkIiTpEI52KmItjU+IcbDRgztiIsChjWEbqnh0jZPVB38oePFUsL6vxm+nsjTE617GlcoTOeHmAgDDZyTn78H0BLoz7Bziof9WvTOhbmct44ag0lhh5hFYHMWYfC43GaPj6y0I/Oo
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflare
