apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  serviceAccountTemplate:
    metadata:
      name: provider-kubernetes
