apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  encryptedData:
    ARGOCD_AUTH_TOKEN: <replace-with-kubeseal-output>
    BACKEND_SECRET: <replace-with-kubeseal-output>
    GITHUB_TOKEN: <replace-with-kubeseal-output>
  template:
    metadata:
      name: backstage-secrets
      namespace: backstage
