---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-repo-creds
  namespace: argocd
spec:
  encryptedData:
    sshPrivateKey: AgBeO+jJ2y5r3heqPbIXAVzkZZLarnuyEhYM0Lqn8U9zBDWvfoYwypWPVkv21MYtVu+4fh+c7bGxHwZBrFokLg9aI28Y9ImtqpGviFXUAc11vDBzc8v4as4mzhAQAZm4JVWKy6Zg7oJ4NxjHLmw211h5jYXPhrJyWyBH7/AUhhorfWz44LaKBLMjOavtg5wL+aicp9iCeeXphEGnw+U12Y+1E2cg78ZqoSZjGM5xMbJNGsvMk1p040lGJLxqcLeGsCXjiR3iYCnoHPxyvVnO2sXSbPuXamYCn3C75q1EBQKFBW5ga6jDdV2n6BJplYd/8cgbd1XfPhjbBts610iNm1kbqbaGk32t8qBfETzdRF2TSBAZ3kgj3cqf9cFEOoLx+feazsLy7HXCmLaCF1E8fRTj6D5WiYIVrgE76Hh2b0dAirh6RWcY3uuv/as/21thbN4x9VXHB1fX5uu6HZRYDS0QiBMtXertgg/Cy11Z7kVpVN/sirR/20b59ackccLTj65s5l5wxDsZiPnBNweKQIhvLk+blT8y8Vh6Bzfzl24A/UcXUVGKuQhvhOh3DkziuZyxeZggClyqkGBmNC8MWFOqozVOg/Yc64hR8ICSmk+pLmvuE7yDfK5Guh0u3QAZG0N4aGhzZdxZzWwxUkNmiUvZFeYkEPt5bC68QVv+WxHtKE6egm6uEcbu76ygVOJvU2GXDH0C1RkjU6OPpdW95YQMGUyFb9+Cshx44yIHq+dWJ4PHuecJc4W4kZpzDkDOXkxTNXBDepO+DcpiwYTyKU8bDMFhZmiwFyVUChMQbCGihke0HUOkUJSjns8+xH3AfR00ZUg7yVgjLmoKSdjb2k9iYd6l3UvPAmH3vb/pfU73nCZubvsIusj4UsiozJRqC7g4wpyA8haZFGID7akiBgNmITzkZ3i+aVDcM7cLoXOMyp0bY5QuKtH34whbcFuIiLiFxX4iXhcmyoBqbR/8jvxlktgAmk1dYm7zGdYLiiAyrtnX2Lwc8YkJWGNxVEjV7RYNPJVmkeX9XWfF8TkujXRicNBRWx2tJTy8PdTi9asNEMwsIfJ/8VFex/YDgeP6p01four90uSfqJkB2N12LONtolaYatsKSVKAKYXKqeJ8ihKrig/hZ4JwzAaOxCjQfkcKKUltiCtIDLrMBufqCT8pSZJLYKUzHCCQWoD1tbdxD2lPKJ6YEZlqsoYMv+vM+wxsjix5oyI1wEVyjsMgoNHdkCv4xpakmjgkE5U=
  template:
    metadata:
      name: github-repo-creds
      namespace: argocd
