---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-repo-creds
  namespace: argocd
spec:
  encryptedData:
    ssh-privatekey: AgA23Wo0mpQlrMle412789q9WT1+4mrxVIZ17CENweIBX2k8JJWK7NJF0IAXeiFOCRWc+ODW2SanCx0T6UGKgrCsNvz0f48XJFME/WGT1AScNfn7gkqLa2NfClABWz7kMoK/rJX9wrhG/tOuhQvpHwhwLn2Znvgfm86eZQWjOqZnT4wwK9JcSDPzpMhpfhPRSEvAz0oZzGbvAjqE2PDJzzR6Yr6/OULLRgjswdtcMOmSZMFEWV8u9INOGlKzcUuxgPDkF5GEurgHT+3IU5J71+QfBCUnuIi43Y1XILVxunJocoGnirEDHtrss9v+iJg9CgTFL9BeT1IC4GAosUdfGPj0+5V+MmQMbo/HDle7QhLzd2q9DHBc5LWKqf7B2BTboZnTmSxPgPJwege4E59dArFD5COvB4d8HIVMYpDnKeBO13T3CcD5gDqw8uQ2gw/EkwpSTsWPhWLZiisuIgRKzmnmAeV1Fcyso1AS7Tnt0+ICG/Ik6VvZ21NE+kfBW8d3k3bqiSsRvcBqRgNKEf7TtBfgdSjpkNcdpSzZbw1TMRwP5ZDTfI3tKFWskqGu/b1bVWEeMuk2+hWYPe4JTBiTtrZbvqjYBNa85G3Ooh8cxWHh59EQW2hIy0FZB0P0Mxmr8gYiOoAKhhud24MuWwkaPeO1ZyEvR66trInoh1GweuX87OIR4E1yGlG9/D/kO0yVHiJg9bnJKVoiFKLLnGXCP59TyklxaJAUyQRuoAjL2t4kLDAYVJRElSVHZ5XP1W6x0DRLBFoMkWQuCs7d0XJycGh0J9iqyRXAjwPSGIeEdswp+I0sFenFGN5O+XTqHmWPmU6rDdqcux/+7KeHGHNJbTHv1CXFCRiT+3+V6I3T5cl4v+bPsV/U3zoMdf4AuM0rID2v/GnbzvVZY40GWOGY4FjWwF2eXYe1YR1QroSd9uQHvSWdn7pdG8YUT8+WXRF/dNeaZo5kxE8xlJPLZHoGdCJ2mRmkLEKAKg90yqMWUX9WlXXEktJRBRvJxuoYgVpZyh7GHmuD5VlGdNlGTpH0cUYQWkb0UF9vS29NH+5mKOqAESj54SXmFyf8bxc0k4/Rynt+kLx4wmAFGpbxu1a2QR6dLGA10ZxM2/XURF69zjPNz8107QZqBmDaYlg4rbHzV8+UVm5gpTV+eHARKTxAPrncu/HaEnbm2kuPugkdyTBiGK5+9AB7cYmL9yCYStZc+Harww3zOh8etgRqtWJfoUxpVG35QqUEPvMGwkI=
  template:
    metadata:
      name: github-repo-creds
      namespace: argocd
